---
- name: Deploy Mastodon Docker service
  hosts: localhost
  tasks:
    - name: Build Docker image
      docker_image:
        path: ./
        name: my_python_app
        tag: latest
        state: present
        force: yes

    - name: Run container
      docker_container:
        name: mastodon_harvester_{{ ansible_date_time.epoch }}
        image: my_python_app:latest
        command: python3 /app/Mastodon_Harvester.py --token {{ token }} --url {{ url }}
        volumes:
          - "/home/ubuntu/Mastodon:/app"
          - "/home/ubuntu/Mastodon/requirements.txt:/requirements.txt"
        state: started
        restart_policy: always
