- name: Install Docker SDK for Python
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present
      become: yes

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present
      become: yes

- name: Install Docker and build Vue app
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Change directory to Frontend
      shell: cd /home/ubuntu/Frontend
      args:
        chdir: /home/ubuntu/Frontend

    - name: Build Vue app Docker image
      command: docker build -t my-vue-app .
      args:
        chdir: /home/ubuntu/Frontend
      changed_when: false

    - name: Run Vue app container
      command: docker run -p 80:80 -d my-vue-app
      changed_when: false
