version: '3'
services:
  couchdb:
    image: couchdb:latest
    volumes:
      - couchdb_data:/opt/couchdb/data
    ports:
      - 0.0.0.0:5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

volumes:
  couchdb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/db
